### ISSUE TITLE
Release jar?

### ISSUE THREAD

**Issue by timothypratley** [wagjo/diff-cljs#1]
Hi - thanks for making diff-cljs -- it is very useful to me.
Could you please push a release jar?   (it helps avoid dependency checks when building)

**Comment by timothypratley** [comment]
Ah looks like there is a released version here: https://github.com/friemen/diffit

**Comment by wagjo** [comment]
Hi, I'm glad my library is useful. I just deployed a non-snapshot version, the artifact name was changed slightly, it is now `[com.wagjo/diff-cljs "0.2.0"]`

**Comment by timothypratley** [comment]
Great! Thanks @wagjo :)
